### ISSUE TITLE
The type 'Object' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by thetemplar** [mparlak/Flee#1]
![image](https://user-images.githubusercontent.com/5371336/28318237-5898d5d8-6bca-11e7-9e38-9a70ddbceb80.png)

Hello,
I cant compile with FLEE in my .net 4.5 project.

> The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

What do I have to do?

**Comment by mparlak** [comment]
Hi,
Thank you for feedback.
Now I have fixed this error.You can upgrade to version 1.0.3
