### ISSUE TITLE
Unable to cast object of type 'Flee.ExpressionElements.CompareElement' to type 'Flee.ExpressionElements.LogicalBitwise.AndOrElement'

### ISSUE THREAD

**Issue by RLaptev** [mparlak/Flee#15]
I'm getting Unable to cast object of type 'Flee.ExpressionElements.CompareElement' to type 'Flee.ExpressionElements.LogicalBitwise.AndOrElement' error when executing the following simple code:

```
ExpressionContext context = new ExpressionContext();
VariableCollection variables = context.Variables;
variables["a"] = "foo";
variables["b"] = "bar";
string s = "a = \"foo\" AND (b = \"bar\" OR b = \"foo\")";
IGenericExpression<bool> exp = context.CompileGeneric<bool>(s);
```

But if I change the order of logical operators to the one below (move AND check to the end), it works!
`string s = "(b = \"bar\" OR b = \"foo\") AND a = \"foo\"";`

Thanks.

**Comment by RLaptev** [comment]
never mind, I upgraded to version 1.0.5 from 1.0.4 and the problem is now gone. 
Great project!

**Comment by vesko-k** [comment]
Please, review your NuGet package 1.0.5, assembly for net45 probably is older version, because the issue still exists. For net461 it's ok.
Рeally awesome project! Mine query executed with Flee is 6 times faster than executed with Linq.Dynamic.
