### ISSUE TITLE
NuGet Package issue

### ISSUE THREAD

**Issue by vesko-k** [mparlak/Flee#20]
Please, review your NuGet package 1.0.5, assembly for net45 probably is older version, because the issue #15 ("Unable to cast object of type 'Flee.ExpressionElements.CompareElement' to type 'Flee.ExpressionElements.LogicalBitwise.AndOrElement'") still presents. For net461 it's ok.

**Comment by pvones** [comment]
I can confirm that.

**Comment by mparlak** [comment]
@vesko-k I will fix this and release a new version.
