### ISSUE TITLE
If and cast not working or I don't know how to make them work

### ISSUE THREAD

**Issue by winalex** [mparlak/Flee#22]
I follow blog on codeproject I also saw in code that there is IF Expression and Cast to type but seem parsing never got to them ever? Hope I'm wrong.

//Sample Scenario 1
            ExpressionContext context = new ExpressionContext();
            context.Imports.ImportBuiltinTypes();
            context.Imports.AddType(typeof(Math));
            VariableCollection variables = context.Variables;
            variables.Add("a", 1);
            variables.Add("b", 1);

            try
            {
                // IGenericExpression<bool> e = context.CompileGeneric<bool>("a=1 AND b=0");
                //IGenericExpression<bool> e = context.CompileGeneric<bool>("If(a = 1,a,b)");
                IGenericExpression<int> e = context.CompileGeneric<int>("if(a>b,a,b)");
                int result = e.Evaluate();

                System.Console.WriteLine(result);
            }catch(ExpressionCompileException ex){
                System.Console.WriteLine(ex.Message+" "+ex.Reason);
            }

GET FunctionCallElement: Could find not function 'if(Boolean, Int32, Int32)' UndefinedName
seem like Flee try to find function with name 'if'. Aren't suppose if to be keyword???
Really is hard  to find any docs about how to use it.

If | Conditional | If(a > 100, "greater", "less")
-- | -- | --
Cast | Cast and conversion | cast(100.25, int)
[] | Array index | 1 + arr[i+1]

`
I tried first 2 not working? I'm afraid to check the rest https://www.codeproject.com/Articles/19768/Flee-Fast-Lightweight-Expression-Evaluator I know that is old version but really few pages are available and not on the topic.

**Comment by mparlak** [comment]
you should use it this [way](https://github.com/mparlak/Flee/wiki/Extending)

**Comment by winalex** [comment]
404 not found

**Comment by winalex** [comment]
Not satisfied dough. It losing the purpose of Expression.
if I need to make function for  ex. ifGT(a,b,then,else) instead of "if a>b,then,else" 
and I need to make function for every >,<,>=,<= losing the purpose of Expression
and compared to ex. a*b  why not to Extending to Mul(a,b). Simple, this way is losing the purpose of having ExpressionEvaluator. If I want to write functions I don't need Evaluation :)
Disappointed. :(

**Comment by winalex** [comment]
SyntaxError: unexpected token "if" <IDENTIFIER>, expected one of "NOT", "-", <INTEGER>, <REAL>, <STRING_LITERAL>, "True", "False", <HEX_LITERAL>, <CHAR_LITERAL>, "null", <DATETIME>, <TIMESPAN>, "(", "if", or "cast", on line: 1 column: 1 SyntaxError

so "if" is recognized also first as IDENTIFIER

**Comment by winalex** [comment]
IF should be right there
