### ISSUE TITLE
Flee fails to parse "if" formula

### ISSUE THREAD

**Issue by PeksiV** [mparlak/Flee#24]
I was trying to evaluate following formula "if(13>24;5;0)" on Flee but it fails with error ExpressionCompileException

<code>
var expressioncontext = new ExpressionContext();
expressioncontext.Options.ParseCulture = new System.Globalization.CultureInfo("fi-FI");
expressioncontext.Options.EmitToAssembly = false;
expressioncontext.Imports.AddType(typeof(System.Math));

var expr = expressioncontext.CompileGeneric<double>(line);
var result = expr.Evaluate();

<error>
Flee.PublicTypes.ExpressionCompileException: FunctionCallElement: Could find not function 'if(Boolean; Int32; Int32)'
   at Flee.ExpressionElements.Base.ExpressionElement.ThrowCompileException(String messageKey, CompileExceptionReason reason, Object[] arguments)
   at Flee.ExpressionElements.Base.MemberElement.Resolve(IServiceProvider services)
   at Flee.ExpressionElements.MemberElements.InvocationListElement.Resolve(IList elements, IServiceProvider services)
   at Flee.ExpressionElements.MemberElements.InvocationListElement..ctor(IList elements, IServiceProvider services)
   at Flee.Parsing.FleeExpressionAnalyzer.ExitMemberExpression(Production node)

**Comment by PeksiV** [comment]
Oh actually I have to use comma as separator
So with formula "if(13>24, 5, 0)" exception will be:

Flee.PublicTypes.ExpressionCompileException: SyntaxError: unexpected character ',', on line: 1 column: 9 ---> Flee.Parsing.grammatica_1._5.alpha2.PerCederberg.Grammatica.Runtime.ParserLogException: unexpected character ',', on line: 1 column: 9

**Comment by PeksiV** [comment]
So problem might be that there are two matching patterns for "if" case.
If I comment out "IDENTIFIER" pattern then if formula works fine. Original implementation seems to have check if the length of the pattern match is greater than previous match. Now that check seems to be missing or I haven't find that yet. 

Anyway the "IF" match is overwritten by "IDENTIFIER" match and that's why it fails.

<code>
pattern = new TokenPattern(Convert.ToInt32(ExpressionConstants.IF), "IF", TokenPattern.PatternType.STRING, "if");

pattern = new TokenPattern(Convert.ToInt32(ExpressionConstants.IDENTIFIER), "IDENTIFIER", TokenPattern.PatternType.REGEXP, "[a-z_]\\w*");

<code>

**Comment by PeksiV** [comment]
/**                                                                                                                                                       |      /**
       * The token match status. This class contains logic to ensure that                                                                                       |       * The token match status. This class contains logic to ensure that
       * only the longest match is considered. It also prefers lower token                                                                                      |       * only the longest match is considered.
       * pattern identifiers if two matches have the same length.                                                                                               |  -------------------------------------------------------------------------------------------------------------------------------------------------------------
       */

**Comment by winalex** [comment]
This must be solved (IF) is very important pattern.

https://github.com/mparlak/Flee/issues/22

**Comment by PeksiV** [comment]
PR was merged so this should be fixed now https://github.com/mparlak/Flee/pull/25

**Comment by mparlak** [comment]
Hi @PeksiV @winalex  
New version upgrade for this issue.(1.0.7)

**Comment by PeksiV** [comment]
Thx. I’ll verify fix with that asap
-Peksi

Hae Outlook for iOS<https://aka.ms/o0ukef>
________________________________
