### ISSUE TITLE
Can you please sign the assembly with strong name?

### ISSUE THREAD

**Issue by mk48** [mparlak/Flee#28]
Thanks for the great library.

I want to use in my project and my project is signed (using strong name). So it doesn't accept the unsigned assemblies so could you please [sign the assembly with strong name](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name)

current version (1.0.7) is not a signed one.

![image](https://user-images.githubusercontent.com/3082469/40220270-3a8e5d7c-5a96-11e8-9b3f-135fd7c85615.png)

**Comment by mk48** [comment]
Signed DLL has 'Digital Signatures' tab in properties dialog box.


![image](https://user-images.githubusercontent.com/3082469/40222000-b110854c-5a9b-11e8-8680-d184d8f9f3c0.png)

**Comment by mparlak** [comment]
@mk48 
I released new version.Can you try it?

**Comment by mk48** [comment]
hi @mparlak 

It doesn't have the Digital Signature tab.

Can you check the project's Release/Debug folder? Just right click the Flee dll and select properties. You can see Digital signature tab if the Dll is signed.

![image](https://user-images.githubusercontent.com/3082469/40226773-4051d98c-5aaa-11e8-8a7c-1ba773d12e8f.png)

**Comment by mk48** [comment]
hi @mparlak 

I followed [this link](https://blogs.msdn.microsoft.com/httpcontext/2012/05/24/how-to-digitally-sign-a-strong-named-assembly/) to sign the DLL and I am able to sign the Flee. Please follow the link to make digital signature.

![image](https://user-images.githubusercontent.com/3082469/40344375-249ab2da-5db2-11e8-99b7-132fde12171a.png)

**Comment by mk48** [comment]
all we have to do is create PFX file using makecert.exe (C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\x86) then sign the project using that PFX file (not the snk file) then sign the DLL again using Signtool.exe, that's it.

**Comment by mparlak** [comment]
@mk48 Hi,
I released new version.Can you try it?

**Comment by mk48** [comment]
Thanks @mparlak It's signed :tada:

![image](https://user-images.githubusercontent.com/3082469/40405344-d7843ee4-5e79-11e8-9d1d-74678a15d9c5.png)
