### ISSUE TITLE
[Question] Can't figure out how conditional operators work.

### ISSUE THREAD

**Issue by pamidur** [mparlak/Flee#3]
I'm trying something like:
```c#
IGenericExpression<int> e = context.CompileGeneric<int>(@"if(1 > 2, 1, 2)");
```

I'm getting
```
Could find not function 'if(Boolean; Int32; Int32)'
```

Have I missed anything?

**Comment by drechema** [comment]
I have a similar problem. In my case using "if(1=1, 1, 2)" I get:
SyntaxError: unexpected character ',', on line: 1 column: 7

**Comment by drechema** [comment]
The error was with the CultureInfo used. Fixed if I used:
context.Options.ParseCulture = CultureInfo.InvariantCulture;
After that the problem is still the same as you
Could find not function 'if(Boolean; Int32; Int32)'

**Comment by drechema** [comment]
If useful for anyone. I solve it doing this:

First declare a Class with the IF function

```
public static class CustomFunctions
{
  public static object @if(bool condition, object whenTrue, object whenFalse) {
    if (condition) {
      return whenTrue;
    } else {
      return whenFalse;
    }
  }
}
```

And use it:

```
ExpressionContext context = new ExpressionContext();
context.Imports.AddType(typeof(CustomFunctions));
IDynamicExpression eDynamic = context.CompileDynamic("IF(true,1,0)");
```
