### ISSUE TITLE
Decimal number literal

### ISSUE THREAD

**Issue by paulbir** [mparlak/Flee#34]
All real numbers in formula are cast to double I guess. So this:

```
var context = new ExpressionContext();
context.Variables.ResolveVariableType += Variables_ResolveVariableType;
context.CompileDynamic("0.1 + a");

void Variables_ResolveVariableType(object sender, ResolveVariableTypeEventArgs e)
{
    e.VariableType = typeof(decimal);
}
```

will cause an exception: "`ArithmeticElement: Operation 'Add' is not defined for types 'Double' and 'Decimal'`".

Is there any literal to force parser cast numeric values to decimals? If there is not, can you add it?

**Comment by bcgrillo** [comment]
I think you can indicate that the number is decimal with the literal "d": "0.1d + a"
Can you try it?

**Comment by paulbir** [comment]
Tried this. Same exception.

**Comment by bcgrillo** [comment]
Sorry, the decimal suffix is "m", not "d"... https://docs.microsoft.com/es-es/dotnet/csharp/language-reference/keywords/decimal

**Comment by paulbir** [comment]
It helped. Thanks.
