### ISSUE TITLE
the function with several parameters can't be interpreted

### ISSUE THREAD

**Issue by paillave** [mparlak/Flee#55]
The example mentioned on https://github.com/mparlak/Flee/wiki/Extending doesn't work.
I get an `ExpressionCompileException`: `unexpected character ',', on line: 1 column: 10`
Here is the exact code that returns me the exception (that is just a copy paste from the documentation):

```CSharp
using Flee.PublicTypes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication8
{
    class Program
    {
        static void Main(string[] args)
        {
            ExpressionContext context = new ExpressionContext();
            context.Imports.AddType(typeof(CustomFunctions));
            context.Variables.Add("a", 100);
            context.Variables.Add("b", 200);
            IDynamicExpression e = context.CompileDynamic("product(a,b) + sum(a,b)");
            int result = (int)e.Evaluate();
        }
    }
    public static class CustomFunctions
    {
        public static int Product(int a, int b)
        {
            return a * b;
        }

        public static int Sum(int a, int b)
        {
            return a + b;
        }
    }
}

```
The actual problem is that on my computer, the default separator seems to be ";". The problem is that if I try to redefine it using `context.ParserOptions.FunctionArgumentSeparator = ','`, it is not taken in consideration and still expects ";" as a function argument separator.

**Comment by paillave** [comment]
I found the issue. I didn't see that I must mention a `context.ParserOptions.RecreateParser();` after redefining options. I work ok now. FYI, in the documentation, it is mentioned that we should make a `context.RecreateParser();` which is not correct.

**Comment by BramCrins** [comment]
Thanks for posting i ran into the same problem and already found the `context.ParserOptions.FunctionArgumentSeparator` . After calling c`ontext.ParserOptions.RecreateParser();` is also worked for me.
