### ISSUE TITLE
null check is broken

### ISSUE THREAD

**Issue by priyank-shenwai** [mparlak/Flee#6]
I am trying to do a null check for an object. My expression is "someType <> null". When I do a context.CompileDynamic("someType <> null") it throws ExpressionCompileExpression

An unhandled exception of type 'Flee.PublicTypes.ExpressionCompileException' occurred in Flee.dll
Additional information: IdentifierElement: Could not find a field/property/variable with the name 'null'

I pulled down the codeplex version of the same and it works fine with the above expression. Looks like it's broken while porting over

**Comment by andreshd** [comment]
Hi!

I just write the expression like:
` 
string expression = "MyVariable1 <> MyVariable2";
var context = new ExpressionContext();
var vars = context.Variables;
vars.DefineVariable("MyVariable1", typeof(MyType));
vars.DefineVariable("MyVariable2", typeof(MyType));
vars["MyVariable1"] = new MyType { MyProperty1 = "SomValue1" };
vars["MyVariable2"] = null;
IDynamicExpression e = context.CompileDynamic(expression);
var result = e.Evaluate();
`
I hope this works for you!

Regards,

Andres

**Comment by eskaufel** [comment]
Or you could write a smal extensions method (https://github.com/mparlak/Flee/wiki/Extending)

`public static class CustomFunctions
{
   public static bool IsNull(object value)
   {
      return object == null;
   }
   public static bool IsNotNull(object value)
   {
      return object != null;
   }
}`

**Comment by mparlak** [comment]
new version upgrade for this issue.
