### ISSUE TITLE
Flee nuget package issue

### ISSUE THREAD

**Issue by max-ieremenko** [mparlak/Flee#92]
I have 3 projects

**Contract.csproj**
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Flee" Version="1.2.2" />
  </ItemGroup>
</Project>
```

**Client.csproj**
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Contract\Contract.csproj" />
  </ItemGroup>
</Project>
```

**Server.csproj**
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Contract\Contract.csproj" />
  </ItemGroup>
</Project>
```

Both `Client` and `Server` share the reference to nuget package [Flee](https://www.nuget.org/packages/Flee/1.2.2).
Due to the package design i have 3 issues in the Client.

**issue 1**
- Client.exe (net472) => Contract.dll (netstandard2.0) => Flee.NetStandard20.dll
Flee.Net45.dll is missing in the build output

**issue 2**
- i try to fix the build output by referencing Flee package from Client.csproj
- Client.exe (net472) => Contract.dll (netstandard2.0) => Flee.NetStandard20.dll
- Client.exe (net472) => Flee.Net45.dll
there are 2 Flee implementations

**issue 3**
because Client and Contract reference different flee assemblies,  types from Flee.Net45.dll are not compatible to types from Flee.NetStandard20.dll

**Comment by hunkydoryrepair** [comment]
should just use Flee.NetStandard20.dll.  Try removing any reference to Flee.Net45.dll in the dependencies.

**Comment by max-ieremenko** [comment]
> Try removing any reference to Flee.Net45.dll in the dependencies

as you can see from the example there is only PackageReference to Flee.
How i can remove reference to Flee.Net45.dll?
