### ISSUE TITLE
Flee nuget package update

### ISSUE THREAD

**Issue by Innotech-Ameen-Alqattow** [mparlak/Flee#94]
last, flee version on NuGet from 1/18/2019
and there some pr like https://github.com/mparlak/Flee/pull/60 I need it in my project so can you please do new NuGet release

**Comment by hunkydoryrepair** [comment]
I had to incorporate my own build.  The crashing bugs were prohibitive. 
Should we fork and make our own NuGet release? @mparlak hasn't been active for about 20 months.

**Comment by Ameen-Alqattow** [comment]
Finally, we have a new NuGet release
